### ISSUE TITLE
Add support for UITextView

### ISSUE THREAD

**Issue by asifbilal786** [oleghnidets/TweeTextField#11]
Please provide support for UITextView.

**Comment by asifbilal786** [comment]
@oleghnidets when do you plan to work on it? Actually I need to implement in my current application.

**Comment by oleghnidets** [comment]
Hi @asifbilal786 
I do not have time for now. I will try to do that asap. But I cannot promise that it will be soon. Maybe, within 2-3 weeks, as it takes long time to have it implemented. 

Could you, please, describe how Text View should look? The same functionality as TweeTextField (even bottom line)?

**Comment by asifbilal786** [comment]
Okay no problem @oleghnidets . Just let me know when you finish working on this feature.

Yes, you are right about Text View. I think it should be the same as TweeTextField with easy multiline support.

**Comment by oleghnidets** [comment]
Hi, 
I keep in mind this issue. But for now I don't have enough time to implement the feature.
I will do my best.

**Comment by Idomo** [comment]
Hi @oleghnidets, Have you started working on this?
I also want to use this library on my current app and this support can be great for me.

**Comment by oleghnidets** [comment]
@Idomo No, I haven't. I have lack of time now :(

**Comment by Idomo** [comment]
Hi @oleghnidets, Whats up?
Have you started working on this? I really like to use this in my current application, I couldn't find any library that will add the `UITextView`'s multiple line future to the `UITextField` so I will be able to use your library on it and have multiple line option in the same time.

**Comment by oleghnidets** [comment]
Hi, 
My bad, I didn't start work on that. But I see you really need this, so I do my best and start working soon. Probably, I will create separated repository and implement this feature.

**Comment by Idomo** [comment]
Thank you very much 🙏🏻

**Comment by dfmarulanda** [comment]
any updates on this? do you need some help?

**Comment by Idomo** [comment]
@Dfmarulanda any help will be appreciated, if you’re able to help.

**Comment by Idomo** [comment]
Hi @oleghnidets, have you started working on this?
I really want to use it and I'm planing release pretty big update for my app soon, so I'd like to make it look matched with the great `TweeTextField`s (right now I'm using [UITextView-Placeholder](https://github.com/devxoul/UITextView-Placeholder), but it doesn't really fits the style or the abilities (animation etc.) of the `TweeTextField`s).

**Comment by oleghnidets** [comment]
Hi @Idomo 
Good news, I have started working on that :) 
Bad news, I met some troubles because UITextView is a bit different. And it is not easy to just move existing logic. So I did tiny progress in front of that. But I believe it will go better when I implement placeholder - the hardest part of the functionality.

**Comment by oleghnidets** [comment]
Hi there,
Unfortunatly, it took me long time :( 
But `TweeTextField` will come soon.. I will do some testing and add CocoaPods coming week. 

https://github.com/oleghnidets/TweeTextView

**Comment by AndreiApostoiu** [comment]
Any update on this?

**Comment by oleghnidets** [comment]
Hey there,
Sorry guys, I gave up 😢 I don't think I can implement it because a new library requires constant time and motivation.

Please, [revise sources](https://github.com/oleghnidets/TweeTextView) if the feature still required. If you wish you may create PR, I'll unarchive project then. Also, I believe it should be easier to implement the desired UI/animation having SwiftUI. 

Thanks for your interest in my work! I do appreciate that.
