### ISSUE TITLE
[Enhancement] custom placeholder color at active state

### ISSUE THREAD

**Issue by kokitang** [oleghnidets/TweeTextField#20]

**Comment by oleghnidets** [comment]
Hi @kokitang ,
I would appreciate if you can describe more details. Thanks

**Comment by kokitang** [comment]
For example, textfield's placeholder color is gray when it is not editing, but be red when editing.
Now we can only set placeholderColor for both state, ie gray color in both editing & non-editing state.

**Comment by oleghnidets** [comment]
Hi there,

I tried to implement this feature. But it requires a lot of time because it may breaks existing functionality.
I attached an example of possible functionality. It is not full functionality you want. Just initial implementation. Please, check it out.

[AnimatedTextField.swift.zip](https://github.com/oleghnidets/TweeTextField/files/2383798/AnimatedTextField.swift.zip)
